export const nutients = {
  nutrients: [
    {
      attr_id: 301,
      usda_tag: "CA",
      name: "Calcium, Ca",
      unit: "mg",
      natural_common: 1,
      item_cpg: 1,
      item_restaurant: 1,
      Notes: "",
      bulk_csv_field: "nf_calcium_mg",
    },
    {
      attr_id: 205,
      usda_tag: "CHOCDF",
      name: "Carbohydrate, by difference",
      unit: "g",
      natural_common: 1,
      item_cpg: 1,
      item_restaurant: 1,
      Notes: "",
      bulk_csv_field: "nf_total_carbohydrate",
    },
    {
      attr_id: 601,
      usda_tag: "CHOLE",
      name: "Cholesterol",
      unit: "mg",
      natural_common: 1,
      item_cpg: 1,
      item_restaurant: 1,
      Notes: "",
      bulk_csv_field: "nf_cholesterol",
    },
    {
      attr_id: 208,
      usda_tag: "ENERC_KCAL",
      name: "Energy",
      unit: "kcal",
      natural_common: 1,
      item_cpg: 1,
      item_restaurant: 1,
      Notes: "",
      bulk_csv_field: "nf_calories",
    },
    {
      attr_id: 606,
      usda_tag: "FASAT",
      name: "Fatty acids, total saturated",
      unit: "g",
      natural_common: 1,
      item_cpg: 1,
      item_restaurant: 1,
      Notes: "",
      bulk_csv_field: "nf_saturated_fat",
    },
    {
      attr_id: 204,
      usda_tag: "FAT",
      name: "Total lipid(fat)",
      unit: "g",
      natural_common: 1,
      item_cpg: 1,
      item_restaurant: 1,
      Notes: "",
      bulk_csv_field: "nf_total_fat",
    },
    {
      attr_id: 605,
      usda_tag: "FATRN",
      name: "Fatty acids, total trans",
      unit: "g",
      natural_common: 1,
      item_cpg: 1,
      item_restaurant: 1,
      Notes: "",
      bulk_csv_field: "nf_trans_fatty_acid",
    },
    {
      attr_id: 303,
      usda_tag: "FE",
      name: "Iron FE",
      unit: "mg",
      natural_common: 1,
      item_cpg: 1,
      item_restaurant: 1,
      Notes: "",
      bulk_csv_field: "nf_iron_mg",
    },
    {
      attr_id: 291,
      usda_tag: "FIBTG",
      name: "Fiber, total dietary",
      unit: "g",
      natural_common: 1,
      item_cpg: 1,
      item_restaurant: 1,
      Notes: "",
      bulk_csv_field: "nf_dietary_fiber",
    },
    {
      attr_id: 306,
      usda_tag: "K",
      name: "Potassium, K",
      unit: "mg",
      natural_common: 1,
      item_cpg: 1,
      item_restaurant: 1,
      Notes: "",
      bulk_csv_field: "nf_potassium",
    },
    {
      attr_id: 307,
      usda_tag: "NA",
      name: "Sodium, NA",
      unit: "mg",
      natural_common: 1,
      item_cpg: 1,
      item_restaurant: 1,
      Notes: "",
      bulk_csv_field: "nf_sodium",
    },
    {
      attr_id: 203,
      usda_tag: "PROCNT",
      name: "Protein",
      unit: "g",
      natural_common: 1,
      item_cpg: 1,
      item_restaurant: 1,
      Notes: "",
      bulk_csv_field: "nf_protein",
    },
    {
      attr_id: 269,
      usda_tag: "SUGAR",
      name: "Sugars, total",
      unit: "g",
      natural_common: 1,
      item_cpg: 1,
      item_restaurant: 1,
      Notes: "",
      bulk_csv_field: "nf_sugars",
    },
    {
      attr_id: 539,
      usda_tag: "SUGAR_ADD",
      name: "Sugars, added",
      unit: "g",
      natural_common: 1,
      item_cpg: 1,
      item_restaurant: 1,
      Notes: "",
      bulk_csv_field: "nf_added_sugars",
    },
    {
      attr_id: 324,
      usda_tag: "VITD",
      name: "Vitamin D",
      unit: "IU",
      natural_common: 1,
      item_cpg: 1,
      item_restaurant: 1,
      Notes: "",
      bulk_csv_field: "nf_vitamin_d_mcg",
    },
    {
      attr_id: 299,
      usda_tag: "SUGAR_ALC",
      name: "Sugar Alcohol",
      unit: "g",
      natural_common: 0,
      item_cpg: 1,
      item_restaurant: 0,
      Notes: "",
      bulk_csv_field: "",
    },
    {
      attr_id: 1001,
      usda_tag: "NA",
      name: "Erthritol",
      unit: "g",
      natural_common: 0,
      item_cpg: 1,
      item_restaurant: 0,
      Notes: "",
      bulk_csv_field: "",
    },
    {
      attr_id: 1006,
      usda_tag: "NA",
      name: "Allulose",
      unit: "g",
      natural_common: 0,
      item_cpg: 1,
      item_restaurant: 0,
      Notes: "",
      bulk_csv_field: "",
    },
    {
      attr_id: 1002,
      usda_tag: "NA",
      name: "Glycerin",
      unit: "g",
      natural_common: 0,
      item_cpg: 1,
      item_restaurant: 0,
      Notes: "",
      bulk_csv_field: "",
    },
    {
      attr_id: 290,
      usda_tag: "XYL",
      name: "Xylitol",
      unit: "g",
      natural_common: 0,
      item_cpg: 1,
      item_restaurant: 0,
      Notes: "",
      bulk_csv_field: "",
    },
    {
      attr_id: 261,
      usda_tag: "SORB",
      name: "Sorbitol",
      unit: "g",
      natural_common: 0,
      item_cpg: 1,
      item_restaurant: 0,
      Notes: "",
      bulk_csv_field: "",
    },
    {
      attr_id: 260,
      usda_tag: "MANOL",
      name: "Mannitol",
      unit: "g",
      natural_common: 0,
      item_cpg: 1,
      item_restaurant: 0,
      Notes: "",
      bulk_csv_field: "",
    },
    {
      attr_id: 1003,
      usda_tag: "NA",
      name: "Maltitol",
      unit: "g",
      natural_common: 0,
      item_cpg: 1,
      item_restaurant: 0,
      Notes: "",
      bulk_csv_field: "",
    },
  ],
};
